# Generated by Django 2.2.4 on 2019-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_key', models.IntegerField()),
                ('catalog_no', models.CharField(max_length=4)),
                ('catalog_color', models.CharField(max_length=24)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('2XL', 'Double Xtra Large'), ('3XL', 'Triple Xtra Large')], max_length=4)),
                ('quantity', models.IntegerField()),
                ('catalog_price', models.FloatField()),
                ('is_on_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
